package com.oerms.notification.enums;

public enum NotificationType {
    USER_REGISTERED,
    EXAM_CREATED,
    EXAM_PUBLISHED,
    EXAM_SCHEDULED,
    EXAM_STARTED,
    EXAM_COMPLETED,
    EXAM_CANCELLED,
    RESULT_PUBLISHED,
    RESULT_GRADED,
    ATTEMPT_SUBMITTED,
    ATTEMPT_AUTO_SUBMITTED,
    PASSWORD_RESET,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    SYSTEM_ALERT,
    CUSTOM
}