/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/attempts/{attemptId}/webcam-violation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record webcam violation
         * @description Records webcam/face detection violations
         */
        post: operations["recordWebcamViolation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/violations/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record custom violation
         * @description Records any custom proctoring violation
         */
        post: operations["recordCustomViolation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/tab-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record tab switch
         * @description Records when student switches browser tabs during exam
         */
        post: operations["recordTabSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/save-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save progress
         * @description Auto-save attempt progress
         */
        post: operations["saveProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume attempt
         * @description Resume paused attempt
         */
        post: operations["resumeAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/proctoring/webcam-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload webcam frame
         * @description Upload webcam frame for face detection
         */
        post: operations["uploadWebcamFrame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/proctoring/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload proctoring screenshot
         * @description Upload screenshot for proctoring
         */
        post: operations["uploadScreenshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/proctoring/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send proctoring heartbeat
         * @description Regular heartbeat for proctoring
         */
        post: operations["sendHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause attempt
         * @description Pause exam attempt (if allowed)
         */
        post: operations["pauseAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/flag-suspicious": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flag attempt as suspicious
         * @description Manually flag attempt for review
         */
        post: operations["flagAsSuspicious"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attempt answers
         * @description Retrieves all answers for an attempt
         */
        get: operations["getAttemptAnswers"];
        put?: never;
        /**
         * Save answer
         * @description Saves or updates an answer for a question in an attempt
         */
        post: operations["saveAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/answers/{questionId}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flag question for review
         * @description Mark question for later review
         */
        post: operations["flagQuestion"];
        /**
         * Unflag question
         * @description Remove review flag from question
         */
        delete: operations["unflagQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/answers/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save multiple answers
         * @description Save answers for multiple questions at once
         */
        post: operations["saveBulkAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit attempt
         * @description Submits a completed exam attempt
         */
        post: operations["submitAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start exam attempt
         * @description Starts a new exam attempt for a student
         */
        post: operations["startAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/bulk/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk submit attempts
         * @description Force submit multiple attempts
         */
        post: operations["bulkSubmit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attempt details
         * @description Retrieves detailed information about an attempt
         */
        get: operations["getAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/time-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get time breakdown
         * @description Time spent per question/section
         */
        get: operations["getTimeBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attempt status
         * @description Get current status and remaining time
         */
        get: operations["getAttemptStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attempt progress
         * @description Get progress details (answered/unanswered)
         */
        get: operations["getAttemptProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/proctoring/violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get violation details
         * @description Get detailed violation logs
         */
        get: operations["getViolations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/proctoring/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get proctoring timeline
         * @description Get chronological timeline of events
         */
        get: operations["getProctoringTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/proctoring/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get proctoring summary
         * @description Get summary of all proctoring events
         */
        get: operations["getProctoringSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/flagged-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get flagged questions
         * @description Get all questions marked for review
         */
        get: operations["getFlaggedQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/can-submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check if can submit
         * @description Validate if attempt can be submitted
         */
        get: operations["canSubmit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attemptId}/answers/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific answer
         * @description Get answer for a specific question
         */
        get: operations["getAnswer"];
        put?: never;
        post?: never;
        /**
         * Clear answer
         * @description Clear/remove answer for a question
         */
        delete: operations["clearAnswer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/suspicious": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get suspicious attempts
         * @description Get all attempts with suspicious activity
         */
        get: operations["getSuspiciousAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/student/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get student attempts
         * @description Retrieves all attempts by a specific student (teacher/admin)
         */
        get: operations["getStudentAttemptsAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search attempts
         * @description Advanced search with filters
         */
        get: operations["searchAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/my-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my attempts
         * @description Retrieves all attempts by the current student
         */
        get: operations["getMyAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/my-attempts/exam/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my attempts for exam
         * @description Retrieves all attempts by current student for a specific exam
         */
        get: operations["getMyExamAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/my-attempts/exam/{examId}/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentExamAttemptsCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/my-attempts/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my attempts count
         * @description Returns total number of attempts by current student
         */
        get: operations["getMyAttemptsCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if attempt service is running
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam attempts
         * @description Retrieves all attempts for a specific exam (teacher/admin)
         */
        get: operations["getExamAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/suspicious": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get suspicious attempts for exam
         * @description Suspicious attempts for specific exam
         */
        get: operations["getSuspiciousExamAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/remaining-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get remaining attempts
         * @description Get number of remaining attempts allowed
         */
        get: operations["getRemainingAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam attempts count
         * @description Returns total number of attempts for an exam
         */
        get: operations["getExamAttemptsCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/completion-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get completion statistics
         * @description Stats on completed vs abandoned attempts
         */
        get: operations["getCompletionStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/can-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check if can start exam
         * @description Validate if student can start new attempt
         */
        get: operations["canStartAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/average-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get average completion time
         * @description Average time taken to complete exam
         */
        get: operations["getAverageCompletionTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/exam/{examId}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam attempt analytics
         * @description Analytics across all attempts for exam
         */
        get: operations["getExamAttemptAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all attempts
         * @description Retrieves all attempts in the system (admin only)
         */
        get: operations["getAllAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Bulk delete attempts
         * @description Delete multiple attempts
         */
        delete: operations["bulkDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        SaveProgressRequest: {
            /** Format: uuid */
            currentQuestionId?: string;
            /** Format: int32 */
            currentQuestionIndex?: number;
        };
        ApiResponseAttemptResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptResponse"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        AttemptAnswerResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            questionId?: string;
            /** Format: int32 */
            questionOrder?: number;
            answerText?: string;
            selectedOptions?: string[];
            flagged?: boolean;
            /** Format: int64 */
            timeSpentSeconds?: number;
            /** Format: int32 */
            marksAllocated?: number;
            /** Format: date-time */
            answeredAt?: string;
        };
        AttemptResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            examId?: string;
            examTitle?: string;
            /** Format: uuid */
            studentId?: string;
            studentName?: string;
            /** Format: int32 */
            attemptNumber?: number;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "PAUSED" | "SUBMITTED" | "AUTO_SUBMITTED" | "ABANDONED" | "COMPLETED" | "CANCELLED";
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            answeredQuestions?: number;
            /** Format: int32 */
            flaggedQuestions?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: int32 */
            examDurationInMinutes?: number;
            /** Format: int32 */
            timeTakenSeconds?: number;
            /** Format: int32 */
            tabSwitches?: number;
            /** Format: int32 */
            webcamViolations?: number;
            autoSubmitted?: boolean;
            notes?: string;
            answers?: components["schemas"]["AttemptAnswerResponse"][];
        };
        ProctoringHeartbeatRequest: {
            /** Format: uuid */
            currentQuestionId?: string;
            isWindowFocused?: boolean;
            /** Format: date-time */
            timestamp?: string;
        };
        FlagSuspiciousRequest: {
            reason?: string;
            flaggedBy?: string;
        };
        SaveAnswerRequest: {
            /** Format: uuid */
            questionId?: string;
            answerText?: string;
            selectedOptions?: string[];
            flagged?: boolean;
            /** Format: int64 */
            timeSpentSeconds?: number;
        };
        ApiResponseAttemptAnswerResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptAnswerResponse"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseListAttemptAnswerResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptAnswerResponse"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        SubmitAttemptRequest: {
            /** Format: uuid */
            attemptId?: string;
            notes?: string;
        };
        StartAttemptRequest: {
            /** Format: uuid */
            examId?: string;
        };
        ApiResponseBulkOperationResultDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BulkOperationResultDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        BulkOperationResultDTO: {
            /** Format: int32 */
            totalRequested?: number;
            /** Format: int32 */
            successful?: number;
            /** Format: int32 */
            failed?: number;
            successfulIds?: string[];
            failedItems?: {
                [key: string]: string;
            };
        };
        ApiResponseTimeBreakdownDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TimeBreakdownDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        QuestionTimeDTO: {
            /** Format: uuid */
            questionId?: string;
            /** Format: int32 */
            questionOrder?: number;
            /** Format: int64 */
            timeSpentSeconds?: number;
        };
        TimeBreakdownDTO: {
            /** Format: uuid */
            attemptId?: string;
            /** Format: int64 */
            totalTimeSeconds?: number;
            questionTimeBreakdown?: components["schemas"]["QuestionTimeDTO"][];
        };
        ApiResponseAttemptStatusDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptStatusDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        AttemptStatusDTO: {
            /** Format: uuid */
            attemptId?: string;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "PAUSED" | "SUBMITTED" | "AUTO_SUBMITTED" | "ABANDONED" | "COMPLETED" | "CANCELLED";
            /** Format: date-time */
            startedAt?: string;
            /** Format: int64 */
            elapsedTimeSeconds?: number;
            /** Format: int64 */
            remainingTimeSeconds?: number;
            isExpired?: boolean;
            canSubmit?: boolean;
        };
        ApiResponseAttemptProgressDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptProgressDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        AttemptProgressDTO: {
            /** Format: uuid */
            attemptId?: string;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            answeredQuestions?: number;
            /** Format: int32 */
            unansweredQuestions?: number;
            /** Format: int32 */
            flaggedQuestions?: number;
            /** Format: double */
            completionPercentage?: number;
        };
        ApiResponseListViolationDetailDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ViolationDetailDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ViolationDetailDTO: {
            type?: string;
            severity?: string;
            description?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListProctoringEventDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProctoringEventDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ProctoringEventDTO: {
            eventType?: string;
            /** Format: date-time */
            timestamp?: string;
            description?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        ApiResponseProctoringSummaryDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProctoringSummaryDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ProctoringSummaryDTO: {
            /** Format: uuid */
            attemptId?: string;
            /** Format: int32 */
            totalTabSwitches?: number;
            /** Format: int32 */
            totalWebcamViolations?: number;
            /** Format: int32 */
            totalViolations?: number;
            isSuspicious?: boolean;
        };
        ApiResponseListUUID: {
            success?: boolean;
            message?: string;
            data?: string[];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseCanSubmitDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CanSubmitDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        CanSubmitDTO: {
            canSubmit?: boolean;
            reasons?: string[];
        };
        ApiResponsePageAttemptSummary: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageAttemptSummary"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        AttemptSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            examId?: string;
            examTitle?: string;
            /** Format: uuid */
            studentId?: string;
            studentName?: string;
            /** Format: int32 */
            attemptNumber?: number;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "PAUSED" | "SUBMITTED" | "AUTO_SUBMITTED" | "ABANDONED" | "COMPLETED" | "CANCELLED";
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            answeredQuestions?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: int64 */
            timeTakenSeconds?: number;
            suspicious?: boolean;
        };
        PageAttemptSummary: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AttemptSummary"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageNumber?: number;
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        ApiResponseLong: {
            success?: boolean;
            message?: string;
            /** Format: int64 */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseString: {
            success?: boolean;
            message?: string;
            data?: string;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseListAttemptSummary: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptSummary"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseInteger: {
            success?: boolean;
            message?: string;
            /** Format: int32 */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseCompletionStatsDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CompletionStatsDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        CompletionStatsDTO: {
            /** Format: uuid */
            examId?: string;
            /** Format: int64 */
            totalAttempts?: number;
            /** Format: int64 */
            completedCount?: number;
            /** Format: int64 */
            autoSubmittedCount?: number;
            /** Format: int64 */
            abandonedCount?: number;
            /** Format: double */
            completionRate?: number;
        };
        ApiResponseCanStartAttemptDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CanStartAttemptDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        CanStartAttemptDTO: {
            canStart?: boolean;
            reasons?: string[];
        };
        ApiResponseDouble: {
            success?: boolean;
            message?: string;
            /** Format: double */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseAttemptAnalyticsDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttemptAnalyticsDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        AttemptAnalyticsDTO: {
            /** Format: uuid */
            examId?: string;
            /** Format: int64 */
            totalAttempts?: number;
            /** Format: int64 */
            completedAttempts?: number;
            /** Format: int64 */
            inProgressAttempts?: number;
            /** Format: double */
            averageCompletionTime?: number;
            /** Format: double */
            averageTabSwitches?: number;
            /** Format: double */
            averageWebcamViolations?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recordWebcamViolation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt ID */
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    recordCustomViolation: {
        parameters: {
            query: {
                violationType: string;
            };
            header?: never;
            path: {
                /** @description Attempt ID */
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    recordTabSwitch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt ID */
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    saveProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProgressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    resumeAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptResponse"];
                };
            };
        };
    };
    uploadWebcamFrame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    frame: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    uploadScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    screenshot: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    sendHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProctoringHeartbeatRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    pauseAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptResponse"];
                };
            };
        };
    };
    flagAsSuspicious: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagSuspiciousRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAttemptAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt ID */
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAttemptAnswerResponse"];
                };
            };
        };
    };
    saveAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt ID */
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptAnswerResponse"];
                };
            };
        };
    };
    flagQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    unflagQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    saveBulkAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAnswerRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAttemptAnswerResponse"];
                };
            };
        };
    };
    submitAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAttemptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptResponse"];
                };
            };
        };
    };
    startAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartAttemptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptResponse"];
                };
            };
        };
    };
    bulkSubmit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBulkOperationResultDTO"];
                };
            };
        };
    };
    getAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Attempt ID */
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptResponse"];
                };
            };
        };
    };
    getTimeBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTimeBreakdownDTO"];
                };
            };
        };
    };
    getAttemptStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptStatusDTO"];
                };
            };
        };
    };
    getAttemptProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptProgressDTO"];
                };
            };
        };
    };
    getViolations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListViolationDetailDTO"];
                };
            };
        };
    };
    getProctoringTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProctoringEventDTO"];
                };
            };
        };
    };
    getProctoringSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProctoringSummaryDTO"];
                };
            };
        };
    };
    getFlaggedQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUUID"];
                };
            };
        };
    };
    canSubmit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCanSubmitDTO"];
                };
            };
        };
    };
    getAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptAnswerResponse"];
                };
            };
        };
    };
    clearAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getSuspiciousAttempts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    getStudentAttemptsAdmin: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                /** @description Student ID */
                studentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    searchAttempts: {
        parameters: {
            query?: {
                examId?: string;
                studentId?: string;
                status?: string;
                suspicious?: boolean;
                startDate?: string;
                endDate?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    getMyAttempts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    getMyExamAttempts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                /** @description Exam ID */
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    getStudentExamAttemptsCount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    getMyAttemptsCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getExamAttempts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                /** @description Exam ID */
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    getSuspiciousExamAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAttemptSummary"];
                };
            };
        };
    };
    getRemainingAttempts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInteger"];
                };
            };
        };
    };
    getExamAttemptsCount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    getCompletionStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCompletionStatsDTO"];
                };
            };
        };
    };
    canStartAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCanStartAttemptDTO"];
                };
            };
        };
    };
    getAverageCompletionTime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDouble"];
                };
            };
        };
    };
    getExamAttemptAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttemptAnalyticsDTO"];
                };
            };
        };
    };
    getAllAttempts: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAttemptSummary"];
                };
            };
        };
    };
    bulkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBulkOperationResultDTO"];
                };
            };
        };
    };
}
