/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam by ID
         * @description Retrieves a single exam by its ID
         */
        get: operations["getExam"];
        /**
         * Update exam
         * @description Updates an existing exam (only DRAFT exams can be updated)
         */
        put: operations["updateExam"];
        post?: never;
        /**
         * Delete exam
         * @description Deletes an exam (only DRAFT exams can be deleted)
         */
        delete: operations["deleteExam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update exam schedule
         * @description Modify exam start/end times
         */
        put: operations["updateSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/duration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update exam duration
         * @description Change total duration of exam
         */
        put: operations["updateDuration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new exam
         * @description Creates a new exam in DRAFT status
         */
        post: operations["createExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/validate-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateConfiguration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpublish exam
         * @description Unpublishes an exam (returns it to DRAFT status)
         */
        post: operations["unpublishExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start exam
         * @description Student starts taking an exam and creates an attempt
         */
        post: operations["startExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish exam
         * @description Publishes an exam (makes it available to students)
         */
        post: operations["publishExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/extend-deadline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extend exam deadline
         * @description Extend end time for exam
         */
        post: operations["extendDeadline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate exam
         * @description Create a copy of existing exam
         */
        post: operations["duplicateExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/create-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create exam template
         * @description Save exam as reusable template
         */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete exam
         * @description Student completes an exam
         */
        post: operations["completeExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel exam
         * @description Cancels a published exam with a reason
         */
        post: operations["cancelExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive exam
         * @description Archives an exam (marks it as inactive)
         */
        post: operations["archiveExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/from-template/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create exam from template
         * @description Create new exam using template
         */
        post: operations["createFromTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/bulk/update-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkUpdateStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/bulk/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkPublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/bulk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/bulk/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/with-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam with questions
         * @description Retrieves an exam with all its questions and statistics
         */
        get: operations["getExamWithQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/validate-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate exam for publishing
         * @description Checks if an exam is ready to be published
         */
        get: operations["validateExamForPublish"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["checkReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/questions/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamQuestionCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam prerequisites
         * @description Check prerequisite exams and their completion status
         */
        get: operations["checkPrerequisites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["checkConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check exam availability
         * @description Check if exam is available for student to take
         */
        get: operations["checkExamAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upcoming exams
         * @description Get scheduled exams starting soon
         */
        get: operations["getUpcomingExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam templates
         * @description Get all available exam templates
         */
        get: operations["getTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/teacher/{teacherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get teacher's exams
         * @description Retrieves all exams created by a specific teacher
         */
        get: operations["getTeacherExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Advanced exam search
         * @description Search with multiple filters
         */
        get: operations["searchExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/published": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get published exams
         * @description Retrieves all published and active exams
         */
        get: operations["getPublishedExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/ongoing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ongoing exams
         * @description Retrieves exams that are currently in progress
         */
        get: operations["getOngoingExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/ending-soon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exams ending soon
         * @description Get exams with approaching deadlines
         */
        get: operations["getExamsEndingSoon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/by-subject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exams by subject
         * @description Get all exams for a specific subject
         */
        get: operations["getExamsBySubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/available-for-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my available exams
         * @description Get all exams student can currently take
         */
        get: operations["getMyAvailableExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all exams (Admin)
         * @description Retrieves all exams in the system (admin only)
         */
        get: operations["getAllExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exams/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active exams
         * @description Retrieves all currently active exams
         */
        get: operations["getActiveExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/token-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTokenInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateExamRequest: {
            title?: string;
            description?: string;
            subject?: string;
            /** Format: int32 */
            duration?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: int32 */
            passingMarks?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            allowMultipleAttempts?: boolean;
            /** Format: int32 */
            maxAttempts?: number;
            shuffleQuestions?: boolean;
            shuffleOptions?: boolean;
            showResultsImmediately?: boolean;
            allowReview?: boolean;
            instructions?: string;
            prerequisiteExamIds?: string[];
            negativeMarking?: boolean;
            /** Format: double */
            negativeMarksPerQuestion?: number;
            autoSubmit?: boolean;
            webcamRequired?: boolean;
            fullScreenRequired?: boolean;
            randomizeQuestionOrder?: boolean;
            showQuestionNumbers?: boolean;
            allowQuestionNavigation?: boolean;
            certificateEnabled?: boolean;
            /** Format: uuid */
            certificateTemplateId?: string;
        };
        ApiResponseExamDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamDTO: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** Format: uuid */
            teacherId?: string;
            teacherName?: string;
            subject?: string;
            /** Format: int32 */
            duration?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: int32 */
            passingMarks?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED" | "SCHEDULED" | "ONGOING" | "COMPLETED" | "CANCELLED" | "ARCHIVED";
            isActive?: boolean;
            allowMultipleAttempts?: boolean;
            /** Format: int32 */
            maxAttempts?: number;
            shuffleQuestions?: boolean;
            shuffleOptions?: boolean;
            showResultsImmediately?: boolean;
            allowReview?: boolean;
            instructions?: string;
            isTemplate?: boolean;
            templateName?: string;
            templateDescription?: string;
            prerequisiteExamIds?: string[];
            negativeMarking?: boolean;
            /** Format: double */
            negativeMarksPerQuestion?: number;
            autoSubmit?: boolean;
            webcamRequired?: boolean;
            fullScreenRequired?: boolean;
            randomizeQuestionOrder?: boolean;
            showQuestionNumbers?: boolean;
            allowQuestionNavigation?: boolean;
            certificateEnabled?: boolean;
            /** Format: uuid */
            certificateTemplateId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            createdBy?: string;
            lastModifiedBy?: string;
        };
        UpdateScheduleRequest: {
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
        };
        CreateExamRequest: {
            title: string;
            description?: string;
            subject?: string;
            /** Format: int32 */
            duration: number;
            /** Format: int32 */
            totalMarks: number;
            /** Format: int32 */
            passingMarks?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            allowMultipleAttempts?: boolean;
            /** Format: int32 */
            maxAttempts?: number;
            shuffleQuestions?: boolean;
            shuffleOptions?: boolean;
            showResultsImmediately?: boolean;
            allowReview?: boolean;
            instructions?: string;
            prerequisiteExamIds?: string[];
            negativeMarking?: boolean;
            /** Format: double */
            negativeMarksPerQuestion?: number;
            autoSubmit?: boolean;
            webcamRequired?: boolean;
            fullScreenRequired?: boolean;
            randomizeQuestionOrder?: boolean;
            showQuestionNumbers?: boolean;
            allowQuestionNavigation?: boolean;
            certificateEnabled?: boolean;
            /** Format: uuid */
            certificateTemplateId?: string;
        };
        ApiResponseBoolean: {
            success?: boolean;
            message?: string;
            data?: boolean;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseExamStartResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamStartResponse"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        AttemptResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            examId?: string;
            examTitle?: string;
            /** Format: uuid */
            studentId?: string;
            studentName?: string;
            /** Format: int32 */
            attemptNumber?: number;
            status?: string;
            /** Format: int32 */
            totalQuestions?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: int32 */
            examDurationInMinutes?: number;
            /** Format: int64 */
            timeTakenSeconds?: number;
            /** Format: int32 */
            tabSwitches?: number;
            /** Format: int32 */
            webcamViolations?: number;
            autoSubmitted?: boolean;
        };
        ExamStartResponse: {
            exam?: components["schemas"]["ExamDTO"];
            attempt?: components["schemas"]["AttemptResponse"];
        };
        DuplicateExamRequest: {
            newTitle?: string;
            copyQuestions?: boolean;
        };
        CreateTemplateRequest: {
            templateName?: string;
            description?: string;
        };
        ApiResponseExamTemplateDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamTemplateDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamTemplateDTO: {
            /** Format: uuid */
            id?: string;
            templateName?: string;
            description?: string;
            subject?: string;
            /** Format: int32 */
            duration?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        CreateFromTemplateRequest: {
            title?: string;
            /** Format: int32 */
            duration?: number;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
        };
        BulkStatusUpdateRequest: {
            examIds?: string[];
            /** @enum {string} */
            newStatus?: "DRAFT" | "PUBLISHED" | "SCHEDULED" | "ONGOING" | "COMPLETED" | "CANCELLED" | "ARCHIVED";
        };
        ApiResponseExamWithQuestionsDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamWithQuestionsDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamWithQuestionsDTO: {
            exam?: components["schemas"]["ExamDTO"];
            questions?: components["schemas"]["QuestionResponse"][];
            /** Format: int64 */
            questionCount?: number;
            /** Format: int32 */
            totalMarks?: number;
            statistics?: components["schemas"]["QuestionStatisticsDTO"];
        };
        QuestionResponse: {
            /** Format: uuid */
            id?: string;
            questionText?: string;
            questionType?: string;
            difficulty?: string;
            subject?: string;
            active?: boolean;
        };
        QuestionStatisticsDTO: {
            /** Format: uuid */
            examId?: string;
            /** Format: int64 */
            totalQuestions?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: int64 */
            mcqCount?: number;
            /** Format: int64 */
            trueFalseCount?: number;
            /** Format: int64 */
            shortAnswerCount?: number;
            /** Format: int64 */
            essayCount?: number;
            /** Format: int64 */
            easyCount?: number;
            /** Format: int64 */
            mediumCount?: number;
            /** Format: int64 */
            hardCount?: number;
        };
        ApiResponseExamStatisticsDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamStatisticsDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamStatisticsDTO: {
            /** Format: uuid */
            examId?: string;
            examTitle?: string;
            /** Format: int64 */
            totalQuestions?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: int64 */
            mcqCount?: number;
            /** Format: int64 */
            trueFalseCount?: number;
            /** Format: int64 */
            shortAnswerCount?: number;
            /** Format: int64 */
            essayCount?: number;
            /** Format: int64 */
            easyCount?: number;
            /** Format: int64 */
            mediumCount?: number;
            /** Format: int64 */
            hardCount?: number;
            status?: string;
        };
        ApiResponseExamReadinessDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamReadinessDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamReadinessDTO: {
            /** Format: uuid */
            examId?: string;
            isReady?: boolean;
            issues?: string[];
            warnings?: string[];
            canPublish?: boolean;
        };
        ApiResponseInteger: {
            success?: boolean;
            message?: string;
            /** Format: int32 */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponsePrerequisiteCheckDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PrerequisiteCheckDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        PrerequisiteCheckDTO: {
            allPrerequisitesMet?: boolean;
            prerequisites?: components["schemas"]["PrerequisiteStatus"][];
        };
        PrerequisiteStatus: {
            /** Format: uuid */
            examId?: string;
            examTitle?: string;
            completed?: boolean;
        };
        ApiResponseListExamConflictDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamConflictDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamConflictDTO: {
            /** Format: uuid */
            examId?: string;
            examTitle?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            conflictType?: string;
        };
        ApiResponseExamAvailabilityDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamAvailabilityDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ExamAvailabilityDTO: {
            /** Format: uuid */
            examId?: string;
            isAvailable?: boolean;
            reasons?: string[];
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** Format: int32 */
            duration?: number;
        };
        ApiResponseListExamDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExamDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponsePageExamTemplateDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageExamTemplateDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        PageExamTemplateDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ExamTemplateDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        ApiResponsePageResponseExamDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseExamDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        PageResponseExamDTO: {
            content?: components["schemas"]["ExamDTO"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
            first?: boolean;
            empty?: boolean;
        };
        ApiResponsePageExamDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageExamDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        PageExamDTO: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ExamDTO"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    updateExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    deleteExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    updateDuration: {
        parameters: {
            query: {
                durationMinutes: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    createExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    validateConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    unpublishExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    startExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamStartResponse"];
                };
            };
        };
    };
    publishExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    extendDeadline: {
        parameters: {
            query: {
                extraMinutes: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    duplicateExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DuplicateExamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamTemplateDTO"];
                };
            };
        };
    };
    completeExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    cancelExam: {
        parameters: {
            query?: {
                /** @description Cancellation reason */
                reason?: string;
            };
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    archiveExam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    createFromTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFromTemplateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamDTO"];
                };
            };
        };
    };
    bulkUpdateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    bulkPublish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    bulkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    bulkArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getExamWithQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamWithQuestionsDTO"];
                };
            };
        };
    };
    validateExamForPublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Exam ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    getExamStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamStatisticsDTO"];
                };
            };
        };
    };
    checkReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamReadinessDTO"];
                };
            };
        };
    };
    getExamQuestionCount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInteger"];
                };
            };
        };
    };
    checkPrerequisites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePrerequisiteCheckDTO"];
                };
            };
        };
    };
    checkConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExamConflictDTO"];
                };
            };
        };
    };
    checkExamAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExamAvailabilityDTO"];
                };
            };
        };
    };
    getUpcomingExams: {
        parameters: {
            query?: {
                daysAhead?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExamDTO"];
                };
            };
        };
    };
    getTemplates: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageExamTemplateDTO"];
                };
            };
        };
    };
    getTeacherExams: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sortBy?: string;
                sortDir?: string;
            };
            header?: never;
            path: {
                teacherId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseExamDTO"];
                };
            };
        };
    };
    searchExams: {
        parameters: {
            query?: {
                title?: string;
                subject?: string;
                status?: "DRAFT" | "PUBLISHED" | "SCHEDULED" | "ONGOING" | "COMPLETED" | "CANCELLED" | "ARCHIVED";
                teacherId?: string;
                minDuration?: number;
                maxDuration?: number;
                startDate?: string;
                endDate?: string;
                minTotalMarks?: number;
                maxTotalMarks?: number;
                isActive?: boolean;
                page?: number;
                size?: number;
                sortBy?: string;
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageExamDTO"];
                };
            };
        };
    };
    getPublishedExams: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sortBy?: string;
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseExamDTO"];
                };
            };
        };
    };
    getOngoingExams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExamDTO"];
                };
            };
        };
    };
    getExamsEndingSoon: {
        parameters: {
            query?: {
                hoursAhead?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExamDTO"];
                };
            };
        };
    };
    getExamsBySubject: {
        parameters: {
            query: {
                subject: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageExamDTO"];
                };
            };
        };
    };
    getMyAvailableExams: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageExamDTO"];
                };
            };
        };
    };
    getAllExams: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sortBy?: string;
                sortDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseExamDTO"];
                };
            };
        };
    };
    getActiveExams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExamDTO"];
                };
            };
        };
    };
    getTokenInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
