/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark notification as read */
        put: operations["markAsRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/my/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark all notifications as read */
        put: operations["markAllAsRead"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a notification */
        post: operations["sendNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get notification by ID */
        get: operations["getNotification"];
        put?: never;
        post?: never;
        /** Delete a notification */
        delete: operations["deleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get my notifications */
        get: operations["getMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/my/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unread notifications */
        get: operations["getUnreadNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/my/unread/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unread notification count */
        get: operations["getUnreadCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        SendNotificationRequest: {
            /** Format: uuid */
            userId?: string;
            email?: string;
            /** @enum {string} */
            type?: "USER_REGISTERED" | "EXAM_CREATED" | "EXAM_PUBLISHED" | "EXAM_SCHEDULED" | "EXAM_STARTED" | "EXAM_COMPLETED" | "EXAM_CANCELLED" | "RESULT_PUBLISHED" | "RESULT_GRADED" | "ATTEMPT_SUBMITTED" | "ATTEMPT_AUTO_SUBMITTED" | "PASSWORD_RESET" | "ACCOUNT_LOCKED" | "ACCOUNT_UNLOCKED" | "ROLE_ASSIGNED" | "ROLE_REMOVED" | "SYSTEM_ALERT" | "CUSTOM";
            title?: string;
            message?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            relatedEntityId?: string;
            relatedEntityType?: string;
            actionUrl?: string;
            /** Format: int32 */
            priority?: number;
            sendEmail?: boolean;
            sendSms?: boolean;
            sendInApp?: boolean;
        };
        ApiResponseNotificationDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["NotificationDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        NotificationDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** @enum {string} */
            type?: "USER_REGISTERED" | "EXAM_CREATED" | "EXAM_PUBLISHED" | "EXAM_SCHEDULED" | "EXAM_STARTED" | "EXAM_COMPLETED" | "EXAM_CANCELLED" | "RESULT_PUBLISHED" | "RESULT_GRADED" | "ATTEMPT_SUBMITTED" | "ATTEMPT_AUTO_SUBMITTED" | "PASSWORD_RESET" | "ACCOUNT_LOCKED" | "ACCOUNT_UNLOCKED" | "ROLE_ASSIGNED" | "ROLE_REMOVED" | "SYSTEM_ALERT" | "CUSTOM";
            title?: string;
            message?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status?: "PENDING" | "SENT" | "FAILED" | "CANCELLED";
            isRead?: boolean;
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: uuid */
            relatedEntityId?: string;
            relatedEntityType?: string;
            actionUrl?: string;
            /** Format: int32 */
            priority?: number;
            createdBy?: string;
            lastModifiedBy?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageResponseNotificationDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseNotificationDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        PageResponseNotificationDTO: {
            content?: components["schemas"]["NotificationDTO"][];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
            first?: boolean;
            empty?: boolean;
        };
        ApiResponseListNotificationDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["NotificationDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseLong: {
            success?: boolean;
            message?: string;
            /** Format: int64 */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    markAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    markAllAsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    sendNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendNotificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNotificationDTO"];
                };
            };
        };
    };
    getNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNotificationDTO"];
                };
            };
        };
    };
    deleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getMyNotifications: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseNotificationDTO"];
                };
            };
        };
    };
    getUnreadNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListNotificationDTO"];
                };
            };
        };
    };
    getUnreadCount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
}
