/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single question
         * @description Retrieves a question by ID
         */
        get: operations["getQuestion"];
        /**
         * Update a question
         * @description Updates an existing question
         */
        put: operations["updateQuestion"];
        post?: never;
        /**
         * Delete a question
         * @description Deletes a question from an exam
         */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder questions
         * @description Changes the display order of questions in an exam
         */
        put: operations["reorderQuestions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new question
         * @description Creates a new question for an exam
         */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/internal/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get questions for grading
         * @description Retrieves a batch of questions by their IDs for internal grading use
         */
        post: operations["getQuestionsForGrading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{sourceExamId}/duplicate/{targetExamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate exam questions
         * @description Copies all questions from source exam to target exam (for exam duplication and templates)
         */
        post: operations["duplicateExamQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk create questions
         * @description Creates multiple questions at once
         */
        post: operations["bulkCreateQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all questions for an exam
         * @description Retrieves all questions including answers (for teachers/admins)
         */
        get: operations["getExamQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate exam questions
         * @description Checks if exam has valid questions for publishing
         */
        get: operations["validateExamQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/total-marks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get total marks
         * @description Returns the sum of all question marks for an exam
         */
        get: operations["getTotalMarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam questions summary
         * @description Returns summary information about exam questions
         */
        get: operations["getExamQuestionsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam questions for students
         * @description Retrieves questions without answers for students
         */
        get: operations["getExamQuestionsForStudent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get exam question statistics
         * @description Returns detailed statistics about questions (count by type, difficulty, etc.)
         */
        get: operations["getExamStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get question count
         * @description Returns the total number of questions for an exam
         */
        get: operations["getQuestionCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/exam/{examId}/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete all questions for an exam
         * @description Deletes all questions from an exam
         */
        delete: operations["deleteAllExamQuestions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateQuestionRequest: {
            questionText?: string;
            /** @enum {string} */
            type?: "MCQ" | "MULTIPLE_ANSWER" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY" | "FILL_BLANK" | "MATCHING";
            /** Format: int32 */
            marks?: number;
            /** Format: int32 */
            orderIndex?: number;
            options?: string[];
            correctAnswer?: string;
            explanation?: string;
            /** @enum {string} */
            difficultyLevel?: "EASY" | "MEDIUM" | "HARD";
            imageUrl?: string;
        };
        ApiResponseQuestionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["QuestionDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        QuestionDTO: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            examId?: string;
            questionText?: string;
            /** @enum {string} */
            type?: "MCQ" | "MULTIPLE_ANSWER" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY" | "FILL_BLANK" | "MATCHING";
            /** Format: int32 */
            marks?: number;
            /** Format: int32 */
            orderIndex?: number;
            options?: string[];
            correctAnswer?: string;
            explanation?: string;
            /** @enum {string} */
            difficultyLevel?: "EASY" | "MEDIUM" | "HARD";
            imageUrl?: string;
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseListQuestionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["QuestionDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        CreateQuestionRequest: {
            /** Format: uuid */
            examId: string;
            questionText: string;
            /** @enum {string} */
            type: "MCQ" | "MULTIPLE_ANSWER" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY" | "FILL_BLANK" | "MATCHING";
            /** Format: int32 */
            marks: number;
            /** Format: int32 */
            orderIndex?: number;
            options?: string[];
            correctAnswer: string;
            explanation?: string;
            /** @enum {string} */
            difficultyLevel?: "EASY" | "MEDIUM" | "HARD";
            imageUrl?: string;
        };
        BulkCreateQuestionsRequest: {
            questions: components["schemas"]["CreateQuestionRequest"][];
        };
        ApiResponseBoolean: {
            success?: boolean;
            message?: string;
            data?: boolean;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseInteger: {
            success?: boolean;
            message?: string;
            /** Format: int32 */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseQuestionSummaryDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["QuestionSummaryDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        QuestionStatisticsDTO: {
            /** Format: uuid */
            examId?: string;
            /** Format: int64 */
            totalQuestions?: number;
            /** Format: int32 */
            totalMarks?: number;
            /** Format: int64 */
            mcqCount?: number;
            /** Format: int64 */
            trueFalseCount?: number;
            /** Format: int64 */
            shortAnswerCount?: number;
            /** Format: int64 */
            essayCount?: number;
            /** Format: int64 */
            easyCount?: number;
            /** Format: int64 */
            mediumCount?: number;
            /** Format: int64 */
            hardCount?: number;
        };
        QuestionSummaryDTO: {
            /** Format: uuid */
            examId?: string;
            /** Format: int64 */
            totalQuestions?: number;
            /** Format: int32 */
            totalMarks?: number;
            statistics?: components["schemas"]["QuestionStatisticsDTO"];
        };
        ApiResponseListStudentQuestionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StudentQuestionDTO"][];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        StudentQuestionDTO: {
            /** Format: uuid */
            id?: string;
            questionText?: string;
            /** @enum {string} */
            type?: "MCQ" | "MULTIPLE_ANSWER" | "TRUE_FALSE" | "SHORT_ANSWER" | "ESSAY" | "FILL_BLANK" | "MATCHING";
            /** Format: int32 */
            marks?: number;
            /** Format: int32 */
            orderIndex?: number;
            options?: string[];
            /** @enum {string} */
            difficultyLevel?: "EASY" | "MEDIUM" | "HARD";
            imageUrl?: string;
        };
        ApiResponseQuestionStatisticsDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["QuestionStatisticsDTO"];
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseLong: {
            success?: boolean;
            message?: string;
            /** Format: int64 */
            data?: number;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            /** Format: date-time */
            timestamp?: string;
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionDTO"];
                };
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionDTO"];
                };
            };
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    reorderQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionDTO"];
                };
            };
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionDTO"];
                };
            };
        };
    };
    getQuestionsForGrading: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionDTO"];
                };
            };
        };
    };
    duplicateExamQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceExamId: string;
                targetExamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionDTO"];
                };
            };
        };
    };
    bulkCreateQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCreateQuestionsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionDTO"];
                };
            };
        };
    };
    getExamQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListQuestionDTO"];
                };
            };
        };
    };
    validateExamQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBoolean"];
                };
            };
        };
    };
    getTotalMarks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInteger"];
                };
            };
        };
    };
    getExamQuestionsSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionSummaryDTO"];
                };
            };
        };
    };
    getExamQuestionsForStudent: {
        parameters: {
            query?: {
                shuffle?: boolean;
            };
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListStudentQuestionDTO"];
                };
            };
        };
    };
    getExamStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseQuestionStatisticsDTO"];
                };
            };
        };
    };
    getQuestionCount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLong"];
                };
            };
        };
    };
    deleteAllExamQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
